# Generated by Django 4.0.2 on 2022-02-14 17:31

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('second_name', models.CharField(db_index=True, max_length=50)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to=main_page.models.Customer.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
