# Generated by Django 4.0.2 on 2022-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_userreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_processed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
