# Generated by Django 4.0.2 on 2022-03-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_usercontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='URL'),
        ),
    ]
